### PR TITLE
adding modal to connect to talisman, nova and other

### PR DESCRIPTION
**Pull request by pedroapfilho**
Screenshot 2022-05-31 at 21 29 31

### CODE REVIEW

**Comment by niklabh** [comment]
Thankyou very much. Let me know when its ready for review

**Comment by pedroapfilho** [comment]
I'm waiting for this PR to be merged before I can make this one available: https://github.com/polkadot-js/extension/pull/1076

**Comment by pedroapfilho** [comment]
Hey @antonkhvorov, idk how to integrate Nova, as it is a mobile wallet. Could you check it and see how we can do it here?

**Comment by niklabh** [comment]
On click of login with web3 it is logging in with username and password

**Comment by niklabh** [comment]
On selecting talisman it is still loading polkadot.js

**Pull request merged**
